# Generated by Django 5.1.15 on 2026-03-27 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvenanceQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_type', models.CharField(max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('queried_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provenance_query_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
