# Generated by Django 5.1.15 on 2026-03-27 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(db_index=True, max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moisture_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quality_score', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('graded_at', models.DateTimeField()),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='lots.lot')),
            ],
            options={
                'db_table': 'grading_grade_record',
                'ordering': ['-graded_at'],
            },
        ),
    ]
