# Generated by Django 5.1.15 on 2026-03-27 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bale_count', models.PositiveIntegerField(default=1)),
                ('tobacco_type', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTERED', 'Registered'), ('IN_CURING', 'In Curing'), ('CURED', 'Cured'), ('GRADED', 'Graded'), ('LISTED_FOR_SALE', 'Listed for Sale'), ('SOLD', 'Sold'), ('SETTLED', 'Settled'), ('DISPUTED', 'Disputed')], db_index=True, default='DRAFT', max_length=20)),
                ('blockchain_anchor_hash', models.CharField(blank=True, default='', max_length=66)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lots', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='seasons.season')),
            ],
            options={
                'db_table': 'lots_lot',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='lots_lot_status_dc6803_idx')],
            },
        ),
    ]
