# Generated by Django 5.1.15 on 2026-04-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobacco_monitoring", "0002_satellite_poll_periodic_task"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tobaccofieldpolygon",
            new_name="tobacco_mon_farm_id_98fe8f_idx",
            old_name="tobacco_mon_farm_id_7a8b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="tobaccofieldpolygon",
            new_name="tobacco_mon_provinc_78d2ad_idx",
            old_name="tobacco_mon_provinc_9d0e1f_idx",
        ),
        migrations.AlterField(
            model_name="tobaccofieldpolygon",
            name="crop_type",
            field=models.CharField(
                db_index=True,
                default="tobacco",
                help_text="Crop type; default tobacco.",
                max_length=64,
            ),
        ),
    ]
