# Generated by Django 5.1.15 on 2026-03-27 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('HARVESTING', 'Harvesting'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=20)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('expected_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='farms.farm')),
            ],
            options={
                'db_table': 'seasons_season',
                'ordering': ['-crop_year', '-created_at'],
                'unique_together': {('farm', 'crop_year')},
            },
        ),
    ]
