# Generated by Django 5.1.15 on 2026-03-27 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('linked_role', models.CharField(blank=True, default='', max_length=30)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_contact',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_type', models.CharField(choices=[('GENERAL', 'General'), ('ONBOARDING', 'Onboarding'), ('FARM_REGISTRATION', 'Farm Registration'), ('SEASON_CREATION', 'Season Creation'), ('LOT_CREATION', 'Lot Creation'), ('EVENT_CAPTURE', 'Event Capture'), ('DOCUMENT_UPLOAD', 'Document Upload'), ('DISPUTE_CREATION', 'Dispute Creation'), ('GRADING', 'Grading'), ('SALE_RECORDING', 'Sale Recording'), ('SETTLEMENT', 'Settlement'), ('DISPUTE_RESPONSE', 'Dispute Response'), ('AI_QUERY', 'AI Query')], default='GENERAL', max_length=30)),
                ('current_state', models.CharField(default='INIT', max_length=100)),
                ('current_intent', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='whatsapp.whatsappcontact')),
            ],
            options={
                'db_table': 'whatsapp_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppIntentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_intent', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=1.0)),
                ('routed_handler', models.CharField(blank=True, default='', max_length=200)),
                ('ai_used', models.BooleanField(default=False)),
                ('raw_input', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent_logs', to='whatsapp.whatsappconversation')),
            ],
            options={
                'db_table': 'whatsapp_intent_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(blank=True, default='text', max_length=50)),
                ('message_body', models.TextField(blank=True, default='')),
                ('media_url', models.URLField(blank=True, default='')),
                ('media_type', models.CharField(blank=True, default='', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('delivery_status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('UNDELIVERED', 'Undelivered')], default='QUEUED', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.whatsappconversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_message_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(db_index=True, max_length=100)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('send_status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('UNDELIVERED', 'Undelivered')], default='QUEUED', max_length=20)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_logs', to='whatsapp.whatsappcontact')),
            ],
            options={
                'db_table': 'whatsapp_template_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['contact', 'is_active'], name='whatsapp_co_contact_8165e6_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['phone_number', 'direction'], name='whatsapp_me_phone_n_57f816_idx'),
        ),
    ]
