# Generated by Django 5.1.15 on 2026-03-27 12:30

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('CERTIFICATE', 'Certificate'), ('GRADING_SHEET', 'Grading Sheet'), ('DELIVERY_NOTE', 'Delivery Note'), ('INSPECTION_RECORD', 'Inspection Record'), ('PROOF_OF_PAYMENT', 'Proof of Payment'), ('DISPUTE_EVIDENCE', 'Dispute Evidence'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('sha256_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('anchor_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('anchor_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lots.lot')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type', 'created_at'], name='documents_d_documen_0216d9_idx')],
            },
        ),
    ]
