# Generated by Django 5.1.15 on 2026-03-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_distinction_documents"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentfingerprint",
            new_name="documents_d_organiz_4e349f_idx",
            old_name="documents_d_organiz_idx",
        ),
    ]
