# Generated by Django 5.1.15 on 2026-03-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ml_monitoring", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="driftmetrics",
            new_name="ml_monitori_organiz_3b739c_idx",
            old_name="ml_monitorin_organiz_0_idx",
        ),
        migrations.RenameIndex(
            model_name="modelrun",
            new_name="ml_monitori_organiz_7ada3f_idx",
            old_name="ml_monitorin_organiz_idx",
        ),
    ]
