# Generated by Django 5.1.15 on 2026-03-27 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('PLANTING', 'Planting'), ('FERTILIZING', 'Fertilizing'), ('HARVESTING', 'Harvesting'), ('CURING', 'Curing'), ('STORAGE', 'Storage'), ('TRANSPORT', 'Transport'), ('GRADING', 'Grading'), ('SALE', 'Sale'), ('DELIVERY', 'Delivery'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('event_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('anchor_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('anchor_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_events', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_events', to='lots.lot')),
            ],
            options={
                'db_table': 'traceability_trace_event',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['lot', 'event_type'], name='traceabilit_lot_id_eddd64_idx'), models.Index(fields=['lot', 'timestamp'], name='traceabilit_lot_id_280b7b_idx')],
            },
        ),
    ]
