# Generated by Django 5.1.15 on 2026-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceevent',
            name='prev_event_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Previous event hash in the append-only chain (64 hex chars; genesis is all zeros).', max_length=64),
        ),
    ]
