# Generated by Django 5.1.15 on 2026-03-30 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('farms', '0001_initial'),
        ('lots', '0001_initial'),
        ('organizations', '0001_initial'),
        ('seasons', '0001_initial'),
        ('settlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('DOC_DUPLICATE_EXACT', 'Document duplicate (exact hash)'), ('DOC_DUPLICATE_NEAR', 'Document near-duplicate'), ('RECEIPT_SALE_MISMATCH', 'Receipt vs sale mismatch'), ('EVENT_MISSING', 'Missing required trace event'), ('EVENT_SEQUENCE_BREAK', 'Out-of-order / chain break'), ('EVENT_TIME_DELTA_OUTLIER', 'Unrealistic time delta'), ('GRADE_JUMP', 'Grade jump anomaly'), ('GRADE_PRICE_MISMATCH', 'Grade vs price mismatch'), ('YIELD_RESIDUAL_OUTLIER', 'Yield vs forecast residual'), ('VENDOR_RISK', 'Vendor risk signal')], db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWING', 'Reviewing'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('model_version', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_alerts_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='documents.document')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='farms.farm')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='lots.lot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='organizations.organization')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='settlements.settlement')),
            ],
            options={
                'db_table': 'ai_intelligence_anomaly_alert',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('hash_match', 'Hash match'), ('similarity', 'Similarity'), ('rule_violation', 'Rule violation'), ('stat_outlier', 'Statistical outlier'), ('sequence_break', 'Sequence break'), ('vendor_risk', 'Vendor risk')], db_index=True, max_length=32)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='ai_intelligence.anomalyalert')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_evidence', to='organizations.organization')),
            ],
            options={
                'db_table': 'ai_intelligence_anomaly_evidence',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_snapshot', models.CharField(blank=True, choices=[('SMALLHOLDER_FARMER', 'Smallholder Farmer'), ('BUYER_CONTRACTOR', 'Buyer / Contractor'), ('REGULATOR_AUDITOR', 'Regulator / Auditor'), ('SYSTEM_ADMIN', 'System Admin')], default='', max_length=32)),
                ('tool_name', models.CharField(db_index=True, max_length=128)),
                ('request_meta_json', models.JSONField(blank=True, default=dict)),
                ('response_meta_json', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_intelligence_assistant_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_snapshot', models.CharField(choices=[('SMALLHOLDER_FARMER', 'Smallholder Farmer'), ('BUYER_CONTRACTOR', 'Buyer / Contractor'), ('REGULATOR_AUDITOR', 'Regulator / Auditor'), ('SYSTEM_ADMIN', 'System Admin')], max_length=32)),
                ('messages_json', models.JSONField(blank=True, default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_intelligence_assistant_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationMetricRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(db_index=True, max_length=64)),
                ('model_key', models.CharField(db_index=True, max_length=64)),
                ('model_version', models.CharField(blank=True, default='', max_length=64)),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_metric_runs', to='organizations.organization')),
            ],
            options={
                'db_table': 'ai_intelligence_evaluation_metric_run',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('farm', 'Farm'), ('lot', 'Lot'), ('region', 'Region')], db_index=True, max_length=20)),
                ('subject_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('region_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('point_timestamp', models.DateTimeField(db_index=True)),
                ('yhat', models.DecimalField(decimal_places=4, max_digits=14)),
                ('yhat_lower', models.DecimalField(decimal_places=4, max_digits=14)),
                ('yhat_upper', models.DecimalField(decimal_places=4, max_digits=14)),
                ('model_version', models.CharField(db_index=True, max_length=64)),
                ('explain_summary', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_points', to='organizations.organization')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_points', to='seasons.season')),
            ],
            options={
                'db_table': 'ai_intelligence_forecast_point',
                'ordering': ['-point_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_type', models.CharField(choices=[('yield', 'Yield'), ('price', 'Price')], db_index=True, max_length=20)),
                ('model_version', models.CharField(db_index=True, max_length=64)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('summary_why', models.TextField(blank=True, default='', help_text='Human-readable explainability summary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_runs_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='organizations.organization')),
            ],
            options={
                'db_table': 'ai_intelligence_forecast_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('confirmed', 'Confirmed'), ('false_positive', 'False positive'), ('needs_info', 'Needs information')], db_index=True, max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_labels', to='ai_intelligence.anomalyalert')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_review_labels', to='organizations.organization')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_review_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_intelligence_review_label',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['organization', 'status', 'severity'], name='ai_intellig_organiz_4b74a5_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['organization', 'alert_type'], name='ai_intellig_organiz_a10468_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevidence',
            index=models.Index(fields=['organization', 'alert'], name='ai_intellig_organiz_10dbc0_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantauditlog',
            index=models.Index(fields=['organization', 'user'], name='ai_intellig_organiz_10ac16_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantauditlog',
            index=models.Index(fields=['organization', 'tool_name'], name='ai_intellig_organiz_fbd181_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['organization', 'user'], name='ai_intellig_organiz_803bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationmetricrun',
            index=models.Index(fields=['organization', 'metric_name'], name='ai_intellig_organiz_c46406_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastpoint',
            index=models.Index(fields=['organization', 'subject_type', 'subject_id'], name='ai_intellig_organiz_76aa12_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastpoint',
            index=models.Index(fields=['organization', 'season_id'], name='ai_intellig_organiz_eb7886_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['organization', 'model_type', 'status'], name='ai_intellig_organiz_31017d_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlabel',
            index=models.Index(fields=['organization', 'alert'], name='ai_intellig_organiz_859919_idx'),
        ),
    ]
