# Generated by Django 5.1.15 on 2026-03-27 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_type', models.CharField(db_index=True, max_length=50)),
                ('reference_id', models.UUIDField(db_index=True)),
                ('tx_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('chain_id', models.PositiveIntegerField(default=1337)),
                ('contract_address', models.CharField(blank=True, default='', max_length=42)),
                ('method_name', models.CharField(blank=True, default='', max_length=100)),
                ('data_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='SUBMITTED', max_length=20)),
                ('gas_used', models.PositiveBigIntegerField(blank=True, null=True)),
                ('raw_receipt', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'blockchain_receipt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_type', 'reference_id'], name='blockchain__referen_cb9051_idx')],
            },
        ),
    ]
