# Generated by Django 5.1.15 on 2026-05-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0003_tier2_tier3_traceability"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="blockchainreceipt",
            new_name="blockchain__reconci_843f65_idx",
            old_name="blockchain__reconci_5e1d3f_idx",
        ),
        migrations.RenameIndex(
            model_name="custodytransfer",
            new_name="blockchain__lot_id_45e39a_idx",
            old_name="blockchain__lot_id_2c9e4b_idx",
        ),
        migrations.RenameIndex(
            model_name="merkleanchorbatch",
            new_name="blockchain__batch_t_433a1c_idx",
            old_name="blockchain__batch_t_3a6c50_idx",
        ),
    ]
