# Generated by Django 5.1.15 on 2026-03-27 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_record_id', models.UUIDField(db_index=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('payload_type', models.CharField(db_index=True, max_length=50)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('SYNCED', 'Synced'), ('DUPLICATE_IGNORED', 'Duplicate Ignored'), ('VALIDATION_FAILED', 'Validation Failed'), ('PENDING_PROCESSING', 'Pending Processing'), ('ERROR', 'Error')], default='PENDING_PROCESSING', max_length=30)),
                ('remote_object_id', models.UUIDField(blank=True, null=True)),
                ('remote_object_type', models.CharField(blank=True, default='', max_length=50)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_sync_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'status'], name='sync_sync_r_actor_i_e21d6d_idx')],
            },
        ),
    ]
