# Generated by Django 5.1.15 on 2026-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0004_farm_gps_boundary_robustness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="boundary_check_tolerance_m",
            field=models.PositiveSmallIntegerField(
                default=25,
                help_text="Server margin (m) for point-in-farm checks (GPS drift + digitisation).",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="geofence_horizontal_accuracy_m",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Device horizontal accuracy (m) when boundary/GPS was captured.",
                null=True,
            ),
        ),
    ]
