# Generated by Django 5.1.15 on 2026-03-27 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('result', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_error', models.BooleanField(default=False)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_assistant_interaction_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
