# Generated by Django 5.1.15 on 2026-03-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worldready", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="taskcompletionlog",
            new_name="worldready__organiz_4f75e1_idx",
            old_name="worldready__organiz_0_idx",
        ),
        migrations.RenameIndex(
            model_name="userpreference",
            new_name="worldready__organiz_c75e77_idx",
            old_name="worldready__organiz_idx",
        ),
    ]
