# Generated by Django 5.1.15 on 2026-03-30 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerLotAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_lots', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_assignments', to='lots.lot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_lot_assignments', to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations_buyer_lot_assignment',
                'indexes': [models.Index(fields=['organization', 'buyer'], name='organizatio_organiz_325286_idx'), models.Index(fields=['organization', 'lot'], name='organizatio_organiz_1b697a_idx')],
                'unique_together': {('buyer', 'lot')},
            },
        ),
    ]
