# Generated by Django 5.1.15 on 2026-03-30 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('organizations', '0002_ai_forecasting_anomaly_assistant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=512)),
                ('platform', models.CharField(choices=[('android', 'android'), ('ios', 'ios'), ('web', 'web')], default='android', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_registrations', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_device_registration',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_7022fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'token'), name='uniq_user_device_token')],
            },
        ),
    ]
